export interface ImCar {
  vin: string,
nid: string,
color: string,
licenseNumber: string
seats: number,
mileage: number,
carType: string,
licenseEXDate: Date,
year: Number,
availableForRent: boolean,
modelName: string,
brandName: string,
locationOfRent: string,
costPerDay: number,
image: string,
insurance: boolean,
gearBoxType: string,
// FuelType: string,
// RegistrationDate: Date,
// IsActivated: boolean,
// Rate: number,
// RatedPeople: number,
}
